# -*- coding: utf-8 -*-
# """admin

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1F_gAZWwX9gzKodmLZOiVWwDonGLiVm0f
# """

from user import user
class admin(user):
    # Constructor
    def __init__(self, set_first, set_last, set_id):
        self.first_name = set_first
        self.last_name = set_last
        self.id = set_id

    def add_course(self):
      # ADDING FROM USER INPUT
      crn = str(input("Enter an id: "))
      title = str(input("Enter title: "))
      depart = str(input("Enter department: "))
      start_time = str(input("Enter what time of day the start of the class is (ex: 8:00 AM): "))
      end_time = str(input("Enter what time of day the end of the class is (ex: 12:00 PM): "))
      days = str(input("Enter what days the class is: "))
      semester = str(input("Enter semester of class: "))
      year = int(input("Enter year of class: "))
      credits = int(input("Enter credits of class: "))
      return(crn, title, depart, start_time, end_time, days, semester, year, credits)

    def remove_course(self):
      crn = str(input("Enter a crn to delete: "))
      # sql_command = """DELETE FROM COURSE WHERE CRN = ?;""", (crn)
      # cursor.execute(sql_command)
      return(crn)

    def add_user(self):  
      uid = input("Enter an id: ")
      fname = input("First name: ")
      lname = input("Last name: ")
      title = input("Enter title: ")
      office = input("Enter an office: ")
      email = input("Enter email: ")
      password = input("Enter password: ")
      return(uid, fname, lname, title, office, email, password)
      #c.execute("""INSERT INTO ADMIN VALUES(?, ?, ?, ?, ?, ?);""", (uid, fname, lname,title, office,email))

    def remove_user(self):
      id = input("Enter an id to delete: ")
      id = str(id)
      return(id)
      #sql_command = """DELETE FROM ADMIN WHERE ID = ?;""", (id)
      #c.execute(sql_command) 
      
    def add_student(self):
      uid = input("Enter an id: ")
      fname = input("First name: ")
      lname = input("Last name: ")
      grad = input("Enter grad year: ")
      major = input("Enter major: ")
      email = input("Enter email: ")
      password = input("Enter password: ")
      return(uid, fname, lname, grad, major, email, password)
      #c.execute("""INSERT INTO STUDENT VALUES(?, ?, ?, ?, ?, ?);""", (uid, fname, lname, grad,major,email))

    def remove_student(self):
      id = input("Enter an id to delete: ")
      id = str(id)
      return(id)
      #sql_command = """DELETE FROM STUDENT WHERE ID = ?;""", (id)
      #c.execute(sql_command) 

    def add_instuctor(self):
      uid = input("Enter an id: ")
      fname = input("First name: ")
      lname = input("Last name: ")
      title = input("Enter title: ")
      hire = input("Enter year of hire: ")
      depart = input("Enter department: ")
      email = input("Enter email: ")
      password = input("Enter password: ")
      return(uid, fname, lname, title, hire, depart, email, password)
      #c.execute("""INSERT INTO INSTRUCTOR VALUES(?, ?, ?, ?, ?, ?, ?);""", (uid, fname, lname,title, hire, depart,email))

    def remove_instructor(self):
      id = input("Enter an id to delete: ")
      id = int(id)
      return(id)
      #sql_command = """DELETE FROM INSTRUCTOR WHERE ID = ?;""", (id)
      #c.execute(sql_command) 

    def unlink_student(self):
      id = str(input("Enter a student's W# without the W: "))
      crn = str(input("Enter a CRN to unlink student: "))
      return(id, crn)

    def unlink_instructor(self):
      id = str(input("Enter an instructor's W# without the W: "))
      crn = str(input("Enter a CRN to unlink instructor: "))
      return(id, crn)